name: ${project.name}
version: ${version}
main: com.ironboundred.bedhomes.BedHomes
description: Adds a home command that is set to the players respawn location.
authors:
  - 'ironboundred'
api-version: '1.20'

dependencies:
  server:
    HuskHomes:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  bedhome.time.bypass:
    description: used to bypass the timed teleport when enabled.
    default: op

commands:
  bed:
    description: teleport to you beds location.