name: ${project.name}
version: ${version}
main: com.ironboundred.bedhomes.BedHomes
description: Adds a home command that is set to the players respawn location.
authors:
  - 'ironboundred'
api-version: '1.20'

dependencies:
  server:
    HuskHomes:
      load: BEFORE
      required: false
      join-classpath: true