version: ${version}
name: ${project.name}
description: Adds a home command that is set to the players respawn location.
author: Ironboundred
api-version: 1.16
softdepend:
 - HuskHomes

main: com.ironboundred.bedhomes.BedHomes

commands:
 bed:
  description: teleport to you beds location.

permissions:
 bedhome.time.bypass:
  description: used to bypass the timed teleport when enabled.
  default: op